/* OpenClaw mock data */
const DATA = {
  skills: [
    { id:'vault',                name:'Memory Vault',     icon:'vault',    tint:'#8a6bd8', desc:'reading ~/memory/output/' },
    { id:'agentmail',            name:'AgentMail',        icon:'agentmail',tint:'#e89658', desc:'polling 6 aliases' },
    { id:'browser',              name:'Browser',          icon:'browser',  tint:'#5ba89d', desc:'chromium · vnc :5901' },
    { id:'linkedin-slow-browse', name:'LinkedIn',         icon:'linkedin', tint:'#3b6fa1', desc:'slow-browse · 1 action / 42s' },
    { id:'github',               name:'GitHub',           icon:'github',   tint:'#3a3028', desc:'gh pr list --state open' },
    { id:'content-creator',      name:'Content',          icon:'content',  tint:'#c98a56', desc:'drafting · 3 platforms' },
    { id:'lead-followup',        name:'Lead Follow-up',   icon:'lead',     tint:'#6aa87f', desc:'14 leads · 2 replied' },
    { id:'proposal-gen',         name:'Proposal Gen',     icon:'proposal', tint:'#b5564f', desc:'growth pkg · $1200' },
    { id:'ui-architect',         name:'UI Architect',     icon:'architect',tint:'#2e6f6a', desc:'wireframing onboarding' },
    { id:'simplyhr-scraping-tool',name:'SimplyHR',        icon:'scraper',  tint:'#a87a48', desc:'scored 38 leads A/B/C' },
    { id:'openclaw-seo-tool',    name:'SEO',              icon:'seo',      tint:'#7a8a3b', desc:'12 kw · intent:buy' },
    { id:'image-gen',            name:'Image-Gen',        icon:'image',    tint:'#d87b6a', desc:'flux-schnell · 1024²' },
    { id:'video-gen',            name:'Video-Gen',        icon:'video',    tint:'#6b5ba8', desc:'idle · locked w/ img' },
    { id:'pc-ops',               name:'PC Ops',           icon:'pcops',    tint:'#4a3a37', desc:'apt upgrade · 128 pkg' },
    { id:'ui-workshop',          name:'UI Workshop',      icon:'workshop', tint:'#e8943b', desc:'3 vite servers up' },
    { id:'social-accounts',      name:'Social',           icon:'social',   tint:'#a85b8a', desc:'whoami: 4 sessions live' },
  ],
  routes: [
    { id:'home',       name:'Home',       icon:'home' },
    { id:'personas',   name:'Personas',   icon:'personas' },
    { id:'composer',   name:'Composer',   icon:'composer' },
    { id:'blog',       name:'Blog Studio',icon:'blog' },
    { id:'media',      name:'Media',      icon:'media' },
    { id:'inbox',      name:'Inbox',      icon:'inbox' },
    { id:'memory',     name:'Memory',     icon:'memory' },
    { id:'skills',     name:'Skills',     icon:'skills' },
    { id:'health',     name:'Health',     icon:'health' },
    { id:'pipelines',  name:'Pipelines',  icon:'pipeline' },
    { id:'proposals',  name:'Proposals',  icon:'proposal' },
    { id:'seo',        name:'SEO',        icon:'seo' },
    { id:'workshop',   name:'Workshop',   icon:'workshop' },
    { id:'github',     name:'GitHub',     icon:'github' },
    { id:'hardware',   name:'Hardware',   icon:'hardware' },
    { id:'sessions',   name:'Sessions',   icon:'sessions' },
    { id:'approvals',  name:'Approvals',  icon:'approval' },
  ],
  persona: 'Terrence Walker (terrencewalker2001)',
  accounts_active: [
    { k:'instagram', h:'@terrencewalker2001', email:'twalker+ig@agentmail.to', last:'2h ago', live:true },
    { k:'threads',   h:'@terrencewalker2001', email:'twalker+th@agentmail.to', last:'5h ago', live:true },
    { k:'reddit',    h:'u/twalker_dev',        email:'twalker+rd@agentmail.to', last:'1d ago', live:true },
    { k:'linkedin',  h:'/in/terrence-walker',  email:'twalker+li@agentmail.to', last:'6h ago', live:true },
  ],
  accounts_blog: [
    { k:'devto',     h:'twalker',           email:'twalker+dev@agentmail.to',   last:'3d ago', live:true },
    { k:'wordpress', h:'twalker2001',       email:'twalker+wp@agentmail.to',    last:'8d ago', live:true },
    { k:'tumblr',    h:'twalker-notes',     email:'twalker+tb@agentmail.to',    last:'—',      live:false },
    { k:'medium',    h:'@twalker',          email:'twalker+md@agentmail.to',    last:'2w ago', live:true },
    { k:'substack',  h:'@openclaw',         email:'twalker+sb@agentmail.to',    last:'4d ago', live:true },
    { k:'hashnode',  h:'twalker.hashnode',  email:'twalker+hn@agentmail.to',    last:'—',      live:false },
  ],
  accounts_skipped: ['bluesky','x'],
  hardware: { pi:'Pi 5 in Freenove case', oled:'SSD1306 0x21 I²C', tailscale_ip:'100.64.226.49', gpu_host:'lamachina (RTX 5070 Ti, Tailscale)' },
  cron: [
    { name:'social-whoami',  at:'09:07',     last:'ok', out:'4 sessions live · linkedin warm' },
    { name:'comfyui-ping',   at:'08:13',     last:'ok', out:'lamachina · 14ms · 14GB free' },
    { name:'agentmail-poll', at:'09:23',     last:'ok', out:'3 new · twalker+li code captured' },
    { name:'weekly-audit',   at:'Mon 07:11', last:'ok', out:'no drift · 0 orphan drafts' },
    { name:'weekly-cleanup', at:'Sun 03:17', last:'ok', out:'freed 4.2GB in /tmp/wan-tmp' },
  ],
  rules: [
    'image-gen and video-gen must never run concurrently (16GB VRAM)',
    'outbound comms require Telegram approval',
    'LinkedIn uses linkedin-slow-browse skill only',
  ],
  drafts: [
    { id:'d_4192', platform:'threads',  status:'pending', ts:'14:02', text:'Shipped a cozy-room dashboard for my agent runtime today…' },
    { id:'d_4191', platform:'linkedin', status:'pending', ts:'13:48', text:'Spent three weeks teaching my raspberry pi to triage leads…' },
    { id:'d_4190', platform:'reddit',   status:'pending', ts:'11:30', text:'[r/selfhosted] Running an AI-agent swarm on a Pi5 + beefy GPU over Tailscale' },
    { id:'d_4188', platform:'instagram',status:'posted',  ts:'09:14', text:'late-night-desk energy · #buildinpublic' },
    { id:'d_4187', platform:'devto',    status:'posted',  ts:'Tue',   text:'Writing an agent that respects your inbox (part 2)' },
    { id:'d_4186', platform:'medium',   status:'rejected',ts:'Mon',   text:'Draft rejected — too much jargon, needs a hook' },
  ],
  leads: {
    new:        [{n:'Aperture HR', m:'simplyhr · score A'}, {n:'Nilavu Labs', m:'linkedin · inbound'}, {n:'PortCraft', m:'simplyhr · score B'}],
    researched: [{n:'Marrow & Co', m:'cto: devika r. · 28 emp'}, {n:'Huron Grove', m:'agency · looking for audit'}],
    contacted:  [{n:'Roslyn Studio', m:'sent · 2d ago'}, {n:'Quartl Systems', m:'sent · 4d ago'}],
    replied:    [{n:'Kestrel Coop', m:'wants to chat thu'}],
    meeting:    [{n:'Windrose', m:'scheduled fri 10am'}],
    proposal:   [{n:'Goldenrod.io', m:'growth pkg · $1200'}, {n:'Ferry & Field', m:'audit · $1500'}],
    closed:     [{n:'Tilefish Media', m:'won · $2500 · may'}],
  },
  proposals: [
    { t:'Starter',  p:'$500',  d:'Discovery + 1-page brief + 3 recs', clients:['Portcraft','Nilavu'], status:'draft' },
    { t:'Growth',   p:'$1200', d:'Dual-persona funnel + 2-week campaign', clients:['Goldenrod.io'], status:'sent' },
    { t:'Full',     p:'$2500', d:'End-to-end runtime install + training', clients:['Tilefish'], status:'won' },
    { t:'Audit',    p:'$1500', d:'Runtime posture + cron/health review', clients:['Ferry & Field','Huron'], status:'draft' },
    { t:'Handbook', p:'$800',  d:'Custom ops handbook + 2 skill templates', clients:['Marrow & Co'], status:'draft' },
  ],
  vite: [
    { n:'onboarding-v3',  port:5173, url:'http://100.64.226.49:5173', up:true },
    { n:'proposal-proof', port:5174, url:'http://100.64.226.49:5174', up:true },
    { n:'comfy-remote',   port:5175, url:'http://100.64.226.49:5175', up:false },
    { n:'vault-browser',  port:5176, url:'http://100.64.226.49:5176', up:true },
  ],
  seo_kw: [
    { k:'self-hosted ai agent', vol:'2.4k', diff:32, intent:'info' },
    { k:'claude runtime pi5',   vol:'120',  diff:12, intent:'buy'  },
    { k:'agentmail alternative',vol:'480',  diff:28, intent:'eval' },
    { k:'comfyui over tailscale',vol:'310', diff:18, intent:'info' },
  ],
  actions_log: [
    '09:41:02  agentmail  fetch · 3 new',
    '09:40:58  linkedin   scroll feed · delay=42s',
    '09:40:12  vault      read output/lead-followup/windrose.md',
    '09:39:47  lead       score = A · windrose',
    '09:38:10  comfyui    warm · flux-schnell loaded',
    '09:37:04  github     pr list --state open (4)',
    '09:36:22  proposal   draft growth pkg for goldenrod',
    '09:35:19  social     whoami · 4/4 sessions live',
    '09:34:40  seo        keyword research · "claude runtime"',
    '09:34:02  pc-ops     apt list --upgradable',
  ],
  inbox_threads: [
    { from:'no-reply@linkedin.com', sub:'New connection request: Devika R.', alias:'+li', when:'09:41', unread:true, code:null },
    { from:'verify@devto',          sub:'Your devto sign-in code: 194820',   alias:'+dev',when:'09:36', unread:true, code:'194820' },
    { from:'reply@reddit.com',      sub:'u/nova_drift replied to your post', alias:'+rd', when:'08:54', unread:false, code:null },
    { from:'no-reply@substack.com', sub:'Subscriber milestone: 100',         alias:'+sb', when:'Tue',   unread:false, code:null },
    { from:'verify@medium.com',     sub:'Confirm your post · code 884102',   alias:'+md', when:'Tue',   unread:true, code:'884102' },
  ],
  memory_tree: {
    raw:   ['linkedin-scrape-2026-04-21.jsonl','devto-drafts-q2.md','comfy-prompts-brain.md'],
    wiki:  ['personas/_index.md','personas/terrence-walker.md','skills/_index.md','skills/linkedin-slow-browse.md','rules/_index.md'],
    output:['lead-followup/_index.md','lead-followup/windrose.md','proposal-gen/_index.md','content-creator/_index.md','openclaw-seo-tool/_index.md'],
  },
};
window.DATA = DATA;
